name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file in backend folder
        run: |
          echo "FUEL_API_CODE=${{ secrets.WEBAPP_FUEL_API_CODE }}" > backend/.env
          echo "HOST=${{ secrets.WEBAPP_HOST }}" >> backend/.env
      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose up -d --build
