name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      # Echo a message indicating the pipeline is running
      - name: Echo pipeline status
        run: echo "The deployment pipeline is now running..."

      - name: Create .env file in backend folder
        run: |
          echo "FUEL_API_CODE=${{ secrets.WEBAPP_FUEL_API_CODE }}" > backend/.env
          echo "HOST=${{ secrets.WEBAPP_HOST }}" >> backend/.env
          echo "CV_API_HOST=${{ secrets.WEBAPP_CV_API_HOST }}" >> backend/.env
          echo "CV_API_KEY=${{ secrets.WEBAPP_CV_API_KEY }}" >> backend/.env
          echo "RESEND_API_KEY=${{ secrets.WEBAPP_RESEND_API_KEY }}" >> backend/.env
          echo "EMAIL_TO=${{ secrets.WEBAPP_EMAIL_TO }}" >> backend/.env
          echo "EMAIL_FROM=${{ secrets.WEBAPP_EMAIL_FROM }}" >> backend/.env

      - name: Deploy with Docker Compose
        run: |
          docker compose -f docker-compose.prod.yaml down
          docker compose -f docker-compose.prod.yaml up -d --build
